services:
  - type: web
    name: smart-garbage-detection
    env: python
    plan: free

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web.app:app --bind 0.0.0.0:10000 --timeout 300

    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: PYTHONUNBUFFERED
        value: "1"
