services:
  - type: web
    name: smart-garbage-detection
    runtime: python
    plan: free
    pythonVersion: 3.10.13
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web.app:app --bind 0.0.0.0:10000 --timeout 300
